#THIS MODULE HOLDS ALL THE BUTTONS THAT ARE CALLED IN THE GRID AND WIN FUNCTIONS AS WELL AS THE CLICKED FUNCTION THAT
# THEN CALLS BACK THE WIN FUNCTIONS
from tkinter import *
import ALL_wins as aw
from tkinter import messagebox
root = Tk()
root.title("Ultimate Tic Tac Toe")
clicked = True
def b_click(b):
    """
This function keeps track of which turn is X's turn and which turn is O's turn on the smaller boards, as well as counts
the number of clicks that occur on a board, in order to ensure that each board can be clicked only as many times as
there are buttons on the board.
                        """
    global clicked, count
    #x goes first then o
    if b["text"] == "" and clicked == True:  # if the text is blank meaning no one has clicked there yet and x is
        # clicking
        b["text"] = 'X'  # then change the text to x
        clicked = False  # change click to O's turn
        # count = count + 1  # keep track of count so we know if its a tie
        aw.win()
        aw.win2()
        aw.win3()
        aw.win4()
        aw.win5()
        aw.win6()
        aw.win7()
        aw.win8()
        aw.win9()
        aw.finalwin()

    elif b["text"] == "" and clicked == False:  # if the text is blank meaning no one has clicked there yet and o is
        # clicking
        b["text"] = 'O'  # then change the text to O
        clicked = True  # change click to X's turn
        # count = count + 1  # keep track of count so we know if its a tie
        aw.win()
        aw.win2()
        aw.win3()
        aw.win4()
        aw.win5()
        aw.win6()
        aw.win7()
        aw.win8()
        aw.win9()
        aw.finalwin()
    else:
        messagebox.showerror("Tic-Tac_Toe", "There is already a mark in that box! \n Please try again!")

def disable_all_buttons(): # this function allows us to disable all the buttons once the game is finished
    """
This button disables all buttons on every board once the game is finished, so they can no longer be clicked and the game
can no longer continue.
                        """
    b1.config(state=DISABLED) #Changes button to disabled if called upon
    b2.config(state=DISABLED)
    b3.config(state=DISABLED)
    b4.config(state=DISABLED)
    b5.config(state=DISABLED)
    b6.config(state=DISABLED)
    b7.config(state=DISABLED)
    b8.config(state=DISABLED)
    b9.config(state=DISABLED)
    b10.config(state=DISABLED)
    b11.config(state=DISABLED)
    b12.config(state=DISABLED)
    b13.config(state=DISABLED)
    b14.config(state=DISABLED)
    b15.config(state=DISABLED)
    b16.config(state=DISABLED)
    b17.config(state=DISABLED)
    b18.config(state=DISABLED)
    b19.config(state=DISABLED)
    b20.config(state=DISABLED)
    b21.config(state=DISABLED)
    b22.config(state=DISABLED)
    b23.config(state=DISABLED)
    b24.config(state=DISABLED)
    b25.config(state=DISABLED)
    b26.config(state=DISABLED)
    b27.config(state=DISABLED)
    b28.config(state=DISABLED)
    b29.config(state=DISABLED)
    b30.config(state=DISABLED)
    b31.config(state=DISABLED)
    b32.config(state=DISABLED)
    b33.config(state=DISABLED)
    b34.config(state=DISABLED)
    b35.config(state=DISABLED)
    b36.config(state=DISABLED)
    b37.config(state=DISABLED)
    b38.config(state=DISABLED)
    b39.config(state=DISABLED)
    b40.config(state=DISABLED)
    b41.config(state=DISABLED)
    b42.config(state=DISABLED)
    b43.config(state=DISABLED)
    b44.config(state=DISABLED)
    b45.config(state=DISABLED)
    b46.config(state=DISABLED)
    b47.config(state=DISABLED)
    b48.config(state=DISABLED)
    b49.config(state=DISABLED)
    b50.config(state=DISABLED)
    b51.config(state=DISABLED)
    b52.config(state=DISABLED)
    b53.config(state=DISABLED)
    b54.config(state=DISABLED)
    b55.config(state=DISABLED)
    b56.config(state=DISABLED)
    b57.config(state=DISABLED)
    b58.config(state=DISABLED)
    b59.config(state=DISABLED)
    b60.config(state=DISABLED)
    b61.config(state=DISABLED)
    b62.config(state=DISABLED)
    b63.config(state=DISABLED)
    b64.config(state=DISABLED)
    b65.config(state=DISABLED)
    b66.config(state=DISABLED)
    b67.config(state=DISABLED)
    b68.config(state=DISABLED)
    b69.config(state=DISABLED)
    b70.config(state=DISABLED)
    b71.config(state=DISABLED)
    b72.config(state=DISABLED)
    b73.config(state=DISABLED)
    b74.config(state=DISABLED)
    b75.config(state=DISABLED)
    b76.config(state=DISABLED)
    b77.config(state=DISABLED)
    b78.config(state=DISABLED)
    b79.config(state=DISABLED)
    b80.config(state=DISABLED)
    b81.config(state=DISABLED)




b1 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b1)) #creates button 1 and sets font type and size as well as dimensions and colour of the button
b2 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b2)) #The same code above is used to create buttons 2-81
b3 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b3))
b4 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b4))
b5 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b5))
b6 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b6))
b7 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b7))
b8 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b8))
b9 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b9))
b10 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b10))
b11 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b11))
b12 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b12))
b13 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b13))
b14 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b14))
b15 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b15))
b16 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b16))
b17 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b17))
b18 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b18))
b19 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b19))
b20 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b20))
b21 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b21))
b22 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b22))
b23 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b23))
b24 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b24))
b25 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b25))
b26 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b26))
b27 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b27))
b28 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b28))
b29 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b29))
b30 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b30))
b31 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b31))
b32 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b32))
b33 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b33))
b34 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b34))
b35 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b35))
b36 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b36))
b37 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b37))
b38 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b38))
b39 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b39))
b40 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b40))
b41 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b41))
b42 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b42))
b43 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b43))
b44 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b44))
b45 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b45))
b46 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b46))
b47 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b47))
b48 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b48))
b49 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b49))
b50 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b50))
b51 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b51))
b52 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b52))
b53 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b53))
b54 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b54))
b55 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b55))
b56 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b56))
b57 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b57))
b58 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b58))
b59 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b59))
b60 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b60))
b61 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b61))
b62 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b62))
b63 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b63))
b64 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b64))
b65 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b65))
b66 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b66))
b67 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b67))
b68 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b68))
b69 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b69))
b70 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b70))
b71 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b71))
b72 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b72))
b73 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b73))
b74 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b74))
b75 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b75))
b76 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b76))
b77 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b77))
b78 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b78))
b79 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b79))
b80 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b80))
b81 = Button(root, text="", font=("Times New Roman", 40), height=1, width=3, bg="white", command=lambda: b_click(b81))

